// src/config/api.config.js
export const BASE_URL = 'https://api.troosolar.com/api';
export const API_ORIGIN = BASE_URL.replace(/\/api\/?$/, '');

// export const BASE_URL = 'http://127.0.0.1:8000/api';

const API = {
    LOGIN: `${BASE_URL}/login`,
    REGISTER: `${BASE_URL}/register`,
    VERIFY_OTP_USER: (userId) => `${BASE_URL}/verify-otp/${userId}`, // 👈 add this
    LINK_ACCOUNTS: `${BASE_URL}/link-accounts`,
    LOAN_CALCULATION: `${BASE_URL}/loan-calculation`,
    MONO_LOAN: (loanCalculationId) => `${BASE_URL}/mono-loan/${loanCalculationId}`,
    LOAN_APPLICATION_DOCS: (monoLoanId) => `${BASE_URL}/loan-application/${monoLoanId}`,
    BENEFICIARY_DETAIL: (monoLoanId) => `${BASE_URL}/beneficiary-detail/${monoLoanId}`,
    LOAN_DETAILS: (monoLoanId) => `${BASE_URL}/loan-details/${monoLoanId}`,
    LOAN_WALLET: `${BASE_URL}/loan-wallet`,
    LOAN_DASHBOARD: `${BASE_URL}/loan-dashboard`,
    CATEGORIES: `${BASE_URL}/categories`,
    CATEGORY_BY_ID: (id) => `${BASE_URL}/categories/${id}`,
    CATEGORY_PRODUCTS: (id) => `${BASE_URL}/categories/${id}/products`,
    PUBLIC_CATEGORY_PRODUCTS: (id) => `${BASE_URL}/website/categories/${id}/products`,
    PRODUCTS_BY_GROUP: (groupType) => `${BASE_URL}/website/products/group/${groupType}`,
    PRODUCTS: `${BASE_URL}/products`,
    PRODUCT_BY_ID: (id) => `${BASE_URL}/products/${id}`,
    BUNDLES: `${BASE_URL}/bundles`,
    BUNDLE_BY_ID: (id) => `${BASE_URL}/bundles/${id}`,
    BUNDLES_BY_TYPE: (type) => `${BASE_URL}/bundles/type/${type}`,
    BUNDLE_DETAILS: (id) => `${BASE_URL}/bundles/${id}/details`,
    MATERIAL_CATEGORIES: `${BASE_URL}/material-categories`,
    MATERIALS_BY_CATEGORY: (categoryId) => `${BASE_URL}/bundles/materials/category/${categoryId}`,
    CUSTOM_BUNDLE_CALCULATE: `${BASE_URL}/bundles/custom/calculate`,
    UPDATE_USER: `${BASE_URL}/update-user`,
    CART: `${BASE_URL}/cart`,
    CART_ITEM: (id) => `${BASE_URL}/cart/${id}`,
    CART_ACCESS: (token) => `${BASE_URL}/cart/access/${token}`,
    DELIVERY_ADDRESS_STORE: `${BASE_URL}/delivery-address/store`,
    DELIVERY_ADDRESS_SHOW: (id) => `${BASE_URL}/delivery-address/show/${id}`,
    DELIVERY_ADDRESS_UPDATE: (id) => `${BASE_URL}/delivery-address/update/${id}`,
    CART_CHECKOUT_SUMMARY: `${BASE_URL}/cart/checkout-summary`,
    ORDERS: `${BASE_URL}/orders`,
    TICKETS: `${BASE_URL}/website/tickets`,
    TICKET_DETAIL: (id) => `${BASE_URL}/website/tickets/${id}`,
    TICKET_REPLY: (id) => `${BASE_URL}/website/tickets/${id}/reply`,
    LOGOUT: `${BASE_URL}/logout`,
    CATEGORY_BRANDS: (id) => `${BASE_URL}/categories/${id}/brands`,
    BRANDS: `${BASE_URL}/brands`,
    BRAND_PRODUCTS: (idsCsv) => `${BASE_URL}/brands/${idsCsv}/products`,
    PRODUCT_REVIEWS: `${BASE_URL}/product-reviews`,
    Fund_Wallet: `${BASE_URL}/fund-wallet`,
    Payment_Confirmation: `${BASE_URL}/order/payment-confirmation`,
    Order_Details: (id) => `${BASE_URL}/order/details/${id}`,
    Forgot_Password: `${BASE_URL}/forget-password`,
    Verify_Reset_Password_OTP: `${BASE_URL}/verify-reset-password-otp`,
    Reset_Password: `${BASE_URL}/reset-password`,
    Transaction_History: `${BASE_URL}/transactions`,
    Get_Referral_Details: `${BASE_URL}/get-referral-details`,
    Withdraw_Referral_Balance: `${BASE_URL}/withdraw`,
    Loan_Calculation_Status: `${BASE_URL}/loan-calculation-stauts`,
    Loan_Calculation_finalize: (id) => `${BASE_URL}/loan-calculation-finalized/${id}`,
    Offered_Loan_Calculation: `${BASE_URL}/offered-loan-calculation`,
    Loan_Payment_Relate: `${BASE_URL}/installments/with-history`,
    Loan_Payment_Repay: (id) => `${BASE_URL}/installments/${id}/pay`,
    Get_All_Addresses: `${BASE_URL}/delivery-address/index`,
    Update_Address: (id) => `${BASE_URL}/delivery-address/update/${id}`,
    Delete_Address: (id) => `${BASE_URL}/delivery-address/delete/${id}`,
    Add_Address: `${BASE_URL}/delivery-address/store`,
    Product_Reviews: `${BASE_URL}/product-reviews`,
    Product_Review_Eligibility: `${BASE_URL}/product-reviews/review-eligibility`,
    Update_Product_Review: (id) => `${BASE_URL}/product-reviews/${id}`,
    Kyc_Upload: `${BASE_URL}/kyc`,




    // BNPL & Buy Now Endpoints
    CONFIG_CUSTOMER_TYPES: `${BASE_URL}/config/customer-types`,
    CONFIG_AUDIT_TYPES: `${BASE_URL}/config/audit-types`,
    CONFIG_LOAN_CONFIGURATION: `${BASE_URL}/config/loan-configuration`,
    CONFIG_CALCULATOR_SETTINGS: `${BASE_URL}/config/calculator-settings`,
    CONFIG_MONO: `${BASE_URL}/config/mono`,
    CONFIG_ADD_ONS: `${BASE_URL}/config/add-ons`,
    CONFIG_STATES: `${BASE_URL}/config/states`,
    CONFIG_CHECKOUT_SETTINGS: `${BASE_URL}/config/checkout-settings`,
    CONFIG_DELIVERY_LOCATIONS: (stateId) => `${BASE_URL}/config/delivery-locations?state_id=${stateId}`,
    BNPL_APPLY: `${BASE_URL}/bnpl/apply`,
    BNPL_APPLICATIONS: `${BASE_URL}/bnpl/applications`,
    BNPL_STATUS: (id) => `${BASE_URL}/bnpl/status/${id}`,
    BNPL_GUARANTOR_INVITE: `${BASE_URL}/bnpl/guarantor/invite`,
    BNPL_GUARANTOR_FORM: `${BASE_URL}/bnpl/guarantor/form`,
    BNPL_GUARANTOR_UPLOAD: `${BASE_URL}/bnpl/guarantor/upload`,
    BNPL_COUNTEROFFER_ACCEPT: `${BASE_URL}/bnpl/counteroffer/accept`,
    BNPL_CONFIRM_DOWN_PAYMENT: (applicationId) => `${BASE_URL}/bnpl/applications/${applicationId}/confirm-down-payment`,
    BNPL_INVOICE: (applicationId) => `${BASE_URL}/bnpl/invoice/${applicationId}`,
    BNPL_PROCESS_CREDIT_CHECK: `${BASE_URL}/bnpl/process-credit-check`,
    BNPL_CREDIT_CHECK_FEE_MONO_INITIATE: `${BASE_URL}/bnpl/credit-check-fee/mono/initiate`,
    BNPL_CREDIT_CHECK_FEE_MONO_VERIFY: `${BASE_URL}/bnpl/credit-check-fee/mono/verify`,
    BNPL_MANDATE_STATUS: (monoCalculationId) => `${BASE_URL}/bnpl/mandate/status/${monoCalculationId}`,
    BNPL_MANDATE_INITIATE: `${BASE_URL}/bnpl/mandate/initiate`,
    BNPL_INSTALLMENT_MONO_DEBIT: (installmentId) => `${BASE_URL}/bnpl/installments/${installmentId}/mono-debit`,
    BNPL_MONO_REPAY_TEST_CONFIG: `${BASE_URL}/bnpl/mono-repay-test/config`,
    BNPL_MONO_REPAY_TEST_STATUS: `${BASE_URL}/bnpl/mono-repay-test/status`,
    BNPL_MONO_REPAY_TEST_BOOTSTRAP: `${BASE_URL}/bnpl/mono-repay-test/bootstrap`,
    BNPL_MONO_REPAY_TEST_REFRESH_DUE: `${BASE_URL}/bnpl/mono-repay-test/refresh-due-dates`,
    BNPL_MONO_CREDIT_STATUS: (sessionId) => `${BASE_URL}/bnpl/mono-credit-status/${sessionId}`,
    USER_MONO_ACCOUNT: `${BASE_URL}/bnpl/user-mono-account`,
    USER_MONO_ACCOUNT_LINK: `${BASE_URL}/bnpl/user-mono-account/link`,
    USER_MONO_ACCOUNT_ALT: `${BASE_URL}/user/mono-account`,
    USER_MONO_ACCOUNT_LINK_ALT: `${BASE_URL}/user/mono-account/link`,
    BNPL_ORDERS: `${BASE_URL}/bnpl/orders`,
    BNPL_ORDER_DETAILS: (orderId) => `${BASE_URL}/bnpl/orders/${orderId}`,
    BNPL_REPAYMENT_SCHEDULE: (applicationId) => `${BASE_URL}/bnpl/applications/${applicationId}/repayment-schedule`,
    BNPL_INSTALLATION_BOOK: `${BASE_URL}/bnpl/installation/book`,
    BUY_NOW_CHECKOUT: `${BASE_URL}/orders/checkout`,
    CALENDAR_SLOTS: `${BASE_URL}/calendar/slots`,
    
    // Site (public) – FAQs editable from backend; form submission recipients (info@, sales@) configured in backend
    SITE_BANNER: `${BASE_URL}/site/banner`,
    SITE_FAQS: `${BASE_URL}/site/faqs`,
    TICKET_SUBJECTS: `${BASE_URL}/site/ticket-subjects`,

    // Audit Request Endpoints
    AUDIT_REQUEST: `${BASE_URL}/audit/request`,
    AUDIT_REQUEST_BY_ID: (id) => `${BASE_URL}/audit/request/${id}`,
    AUDIT_REQUESTS: `${BASE_URL}/audit/requests`,

    // add more when needed
};

export default API;
